### PR TITLE
increased visibility of buttons on the bottom of screen

### PR DESCRIPTION
**Pull request by r-maradiaga**
The two buttons for font size and keyboard shortcuts were hard to see. To change this, I changed the viewport height of the container that holds those buttons to be the same as the viewport height of the header.

### CODE REVIEW

**Comment by bryanmontalvan** [comment]
@RJMaradiaga Could you send me a screenshot of the new look?

**Comment by RJMaradiaga** [comment]
image
image

**Comment by bryanmontalvan** [comment]
@RJMaradiaga This is definitely an improvement, I think making both of the buttons(and their containers) a bit wider would be the best option. Could you mock it up?

**Comment by RJMaradiaga** [comment]
I made two versions, both of which make the buttons taller and wider. 

This is one version that has the actual word "shortcuts" on the button. This option might be good because, when I just started on the website, I didn't have any idea of what the button did so I didn't even click it or hover over it. 

image

This version makes the buttons bigger and wider without the text. 

image

What do you think @bryanmontalvan ?

**Review by bryanmontalvan — DISMISSED** [review]
Looks good to me :+1:

**Pull request closed without merging**
