### PR TITLE
fixed the bug where opening tour while editor is closed didn't highlight editor

### PR DESCRIPTION
**Pull request by samuel-zuk**
ignore the weird commit history, i'm just learning how to use git lol :+1:

### CODE REVIEW

**Comment by jasondkiesling** [comment]
Also, can we remove the console.log in src/actions/sceneActions.js. That was my fault for leaving that in.

**Comment by jasondkiesling** [comment]
Addresses #140

**Comment by samuel-zuk** [comment]
honestly, i think I only changed those functions to arrow functions to try to learn the syntax. you don't need to keep that change.

**Comment by jasondkiesling** [comment]
Can you revert that change and push it to GitHub? I can't update it on your fork. It's best to keep things all following the same syntax.

**Pull request closed without merging**
