### PR TITLE
Reference comes from the right, dependency update, color shift animation, animations use the cursor, scene config doesn't lose work, and tour can highlight editor

### LINKED ISSUE #89: Changing grid/floor/scene options before rendering/saving code loses code in buffer

### LINKED ISSUE #92: Move reference so that it doesn't cover the editor
Adapt the reference so that it comes from the right hand side and is the same size as the viewer.

### LINKED ISSUE #140: MYR tour can't highlight editor when editor is closed
**Steps To Reproduce:**
1. Open MYR
2. Close the editor
3. Launch the tour

### LINKED ISSUE #173: Create color shift animation
Create color shift animation with syntax similar to `colorShift(element, toColor)`. The from color should be set using the value of the cursor.

Discussion should be had on the name of the function. For instance, `shiftColor()` might be clearer.

This is reliant on the completion of #138.

### LINKED ISSUE #183: Tour needs to close reference if open

### PR DESCRIPTION
**Pull request by elenaizotova**
<details>
<summary>Fixed #92 - Editor moved to right side</summary>
The editor is on the right and is smaller to not cover the editor.
</details>
<details>
<summary>Fixed #173 - New color shift animation</summary>
The new animation `colorShift(elementID, color)` was added. This takes an elementID (either a group or a single geometry) and a color to shift to. It takes the color that the original element was and shifts between that color and the new color.
</details>
<details>
<summary>Fixed #89 - Saves code before updating scene config</summary>
The options in the scene config menu now render the scene before updating the setting. This prevents the code from being lost if changed after a render.
</details>
<details>
<summary>Fixed #140 - Tour can't reference editor when closed</summary>
The tour was unable to highlight the editor when the scene was set to view only. The tour now opens the editor and explains how to turn it on and off.
</details>
<details>
<summary>Fixed #183 - Tour needs to close editor after opening it</summary>
The fix for #140 originally opened the editor and didn't close it again. If the tour opened the editor, it closes it at the end of the tour.
</details>

### CODE REVIEW

**Comment by jasondkiesling** [comment]
Confirmed as working on Windows 10 Enterprise with a Chrome browser.

**Comment by samuel-zuk** [comment]
Confirmed as working on (an Ubuntu-based distro of) Linux on Firefox.

**Comment by samuel-zuk** [comment]
Just realized that since the reference section no longer covers up the left side of the screen, the user can now start the tour while the reference section is open, which makes the tour pretty wonky. [screenshot of this](https://imgur.com/mOc5izz).

**Comment by jasondkiesling** [comment]
Awesome. Great catch @samuel-zuk! I opened #183 and assigned that to you.

**Comment by jSwanson99** [comment]
Confirmed as working on Windows 10 Home with Opera browser.
Not sure if #89 was supposed to include a fix for the save buffer being lost when going into view only, but that doesn't seem to be working if it was. A fix for this is in my latest pull request

**Pull request merged**
